name: Build Geode Mod
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Android
          os: ubuntu-latest
          target: Android

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # Forzamos a que use Android directamente para evitar el error de --platform
          target: Android
          # Esto evita que el compilador se detenga por advertencias menores
          combine: true
