name: Build Geode Mod
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Android
          os: ubuntu-latest
          target: Android

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # Esta es la l√≠nea que corrige el error '--platform'
          target: ${{ matrix.config.target }}
